Guide Map and Waypoint Command Implementations
teaconmc/SignMeUp pull request #1
Opened 2021-03-04 18:45 UTC by yuesha-yc

Added command implementations for: 
- /signmeup map list
- /signmeup map open
- /signmeup map open <domain:path>
- /signmeup point list
- /signmeup point list location
- /signmeup point get <domain:path> location

Refactored the command static methods and reformatted some code.

2021-03-04 20:27 UTC, 3TUSK requested changes
For all `StringTextComponent` occurrences, use `TranslationTextComponent` to support i18n.

2021-03-04 20:34 UTC, 3TUSK requested changes
Some code style issues. @ustc-zzzz We might want a style guide…

2021-03-04 20:34 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/GuideMap.java
> +import com.google.gson.*;
No star import

2021-03-04 20:34 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/GuideMap.java
> -    ITextComponent title;
Keep the fields in previous order

2021-03-04 20:34 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/GuideMapManager.java
> -import net.minecraft.client.resources.JsonReloadListener; // To anyone who are shocked: yes this class exists on both side!
That comment is necessary in case someone else is looking at this code.

2021-03-04 20:34 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/GuideMapManager.java
> +import java.util.*;
No star import

2021-03-04 20:34 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/Trigger.java
> +import com.google.gson.*;
No star import

2021-03-04 20:34 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/Trigger.java
> +    public volatile boolean disabled = false;
Keep field in the previous order

2021-03-04 20:34 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/Waypoint.java
> +import com.google.gson.*;
No star import

2021-03-05 03:07 UTC, yuesha-yc commented
> Some code style issues. @ustc-zzzz We might want a style guide…

Should all be fixed now.

2021-03-05 04:05 UTC, 3TUSK requested changes
`StringTextComponent` -> `TranslationTextComponent`, thanks.

2021-03-05 04:05 UTC, 3TUSK commented on .github/pull_request_template.md
> +## Changes
what?

2021-03-05 04:05 UTC, 3TUSK commented on .github/workflows/build.yml
> +# Last update: Sep 29 2020
um we have our own workflows, so this one doesn't belong here.
https://github.com/teaconmc/SimplePermission/blob/1.16-forge/.github/workflows/test-build.yml

2021-03-05 04:05 UTC, 3TUSK commented on src/main/java/org/teacon/signin/command/CommandImpl.java
> +            return Command.SINGLE_SUCCESS;
```suggestion
            src.sendFeedback(new TranslationTextComponent("sign_up.text.list_maps"), false);
            for (GuideMap map : SignMeUp.MANAGER.getAllMaps()) {
                src.sendFeedback(map.getTitle(), false);
            }
```

2021-03-05 04:05 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/Waypoint.java
> +import com.google.gson.JsonSerializer;import com.mojang.brigadier.StringReader;
```suggestion
import com.google.gson.JsonSerializer;
import com.mojang.brigadier.StringReader;
```

2021-03-05 04:05 UTC, 3TUSK commented on src/main/java/org/teacon/signin/data/GuideMap.java
> +import com.google.gson.*;
*no star import…*

2021-03-05 07:12 UTC, 3TUSK approved these changes

2021-03-05 07:13 UTC, 3TUSK commented
There might be oversights but I guess I can deal with those later.

2021-03-05 07:13 UTC, merged

2021-03-05 07:36 UTC, yuesha-yc commented
Appreciated :>